version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    IMAGE_REPO_NAME: product-app-repo
    IMAGE_TAG: latest
    # REPOSITORY_URI can also be defined here for clarity, but setting it in pre_build works with version 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 371077466852.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Building the Spring Boot app with Maven...
      - mvn clean package
      - REPOSITORY_URI=371077466852.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"%s","imageUri":"%s"}]' $IMAGE_REPO_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - target/ProductAppAWS-0.0.1-SNAPSHOT.jar
